### ISSUE TITLE
请问我想用wda的话应该clone哪个呢

### ISSUE THREAD

**Issue by BigWavelet** [sixleaves/WDUSBClient#1]
您好， 之前遇到fb的wda对ios10.x支持不好的情况， 听说你解决了， 我想用一下wda， 请问我该用哪一个呢？ 是[https://github.com/sixleaves/WebDriverAgent](url)这个呢 还是[https://github.com/sixleaves/WDUSBClient/tree/master/WebDriverAgent](url)这个呀，十分感谢

**Comment by sixleaves** [comment]
@BigWavelet `git clone https://github.com/sixleaves/WDUSBClient.git`
这个里面的wda
